In [2]:
import numpy as np

A.) Reproducible Normalization Problem

In [3]:
#This makes sure that the random numbers are reproducible
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5,5))

In [4]:
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]], dtype=int32)

In [5]:
#This normalizes the array
X_normalized = (X - X.mean()) / X.std()
#This prints the normalized array
print(X_normalized)

#This saves the normalized array as "X_normalized.npy"
np.save('X_normalized.npy', X_normalized)

[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


B.) Cubes Divisible by 4 Problem

In [6]:
#This creates an array 
hundred = np.arange(1,101)

In [7]:
#This squares the numbers and shapes the array into a 10X10 grid
tenXten = hundred.reshape(10, 10) **2

In [8]:
tenXten

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [9]:
#This determines all the elements that are divisible by 4
div_by_4 = tenXten[tenXten % 4 == 0]

#This saves the array as "div_by_4.npy"
np.save('div_by_4.npy', div_by_4)

In [10]:
div_by_4

array([    4,    16,    36,    64,   100,   144,   196,   256,   324,
         400,   484,   576,   676,   784,   900,  1024,  1156,  1296,
        1444,  1600,  1764,  1936,  2116,  2304,  2500,  2704,  2916,
        3136,  3364,  3600,  3844,  4096,  4356,  4624,  4900,  5184,
        5476,  5776,  6084,  6400,  6724,  7056,  7396,  7744,  8100,
        8464,  8836,  9216,  9604, 10000])

C.) Above-Mean Squares Problem

In [11]:
#This creates an array from 1-36 and arranges it in a 6x6 matrix
S = np.arange(1, 37) ** 2   
S = S.reshape(6, 6)

S

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

In [12]:
#This calculates the mean
S_mean = np.mean(S)
S_mean

np.float64(450.1666666666667)

In [13]:
#This sets the value above the mean for checking
above_mean = S[S > S_mean]
print(above_mean)
#This gets the shape of above_mean
above_mean.shape

[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


(15,)